apiVersion: v1
kind: Service
metadata:
  labels:
    app: meta-ui
    component: web
  name: meta-ui-service
  namespace: meta-demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: meta-ui
    component: web
